# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields
)
from marshmallow.validate import (
    OneOf
)
from swagger_marshmallow_codegen.fields import (
    DateTime
)


class Collection(Schema):
    id = fields.Integer()
    trigger = fields.String(validate=[OneOf(choices=['background', 'on-demand', 'manual'], labels=[])], attribute='trigger.value')
    ctype = fields.String(validate=[OneOf(choices=['keywords', 'geo'], labels=[])], attribute='ctype.value')
    forecast_id = fields.String()
    kwfile = fields.String()
    locfile = fields.String()
    runtime = DateTime()
    nuts3 = fields.String()
    nuts3source = fields.String()
    status = fields.String(validate=[OneOf(choices=['active', 'inactive'], labels=[])], attribute='status.value')
    started_at = DateTime()
    stopped_at = DateTime()


class CollectorPayload(Schema):
    config = fields.String(description='Config file to init Collector instance')
    trigger = fields.String(validate=[OneOf(choices=['background', 'on-demand', 'manual'], labels=[])])
    ctype = fields.String(validate=[OneOf(choices=['keywords', 'geo'], labels=[])])
    forecast_id = fields.String()
    kwfile = fields.String()
    locfile = fields.String()
    runtime = DateTime()
    nuts3 = fields.String()
    nuts3source = fields.String()


class CollectorResponse(Schema):
    collection = fields.Nested('Collection')
    id = fields.Integer()
