"""empty message

Revision ID: 34ad35a774d2
Revises: fbc3f3b98c09
Create Date: 2018-08-14 11:36:12.707144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ad35a774d2'
down_revision = 'fbc3f3b98c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_twitter_collection', sa.Column('use_pipeline', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_twitter_collection', 'use_pipeline')
    # ### end Alembic commands ###
