"""empty message

Revision ID: 461a504ec8a4
Revises: 8163c029df4e
Create Date: 2018-09-06 14:11:42.946126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '461a504ec8a4'
down_revision = '8163c029df4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_twitter_collection', sa.Column('efas_id', sa.Integer(), nullable=True))
    op.drop_column('virtual_twitter_collection', 'nuts2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_twitter_collection', sa.Column('nuts2', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_column('virtual_twitter_collection', 'efas_id')
    # ### end Alembic commands ###
