"""empty message

Revision ID: 95df01dfc439
Revises: e6a1825635e2
Create Date: 2018-10-29 17:16:03.183371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95df01dfc439'
down_revision = 'e6a1825635e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_twitter_collection', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_twitter_collection', 'created_at')
    # ### end Alembic commands ###
