"""empty message

Revision ID: a0556593ad29
Revises: 69695feaabdb
Create Date: 2019-03-28 16:57:44.938706

"""
from alembic import op
import sqlalchemy as sa

from smfrcore.models.sql.base import LongJSONType

# revision identifiers, used by Alembic.
revision = 'a0556593ad29'
down_revision = '69695feaabdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_tweet',
                    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('collection_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('lang', sa.String(length=3), nullable=True),
                    sa.Column('ttype', sa.String(length=20), nullable=False),
                    sa.Column('nuts2', sa.String(length=10), nullable=True),
                    sa.Column('nuts2_source', sa.String(length=100), nullable=True),
                    sa.Column('lat', sa.Float(), nullable=True),
                    sa.Column('lon', sa.Float(), nullable=True),
                    sa.Column('annotations', LongJSONType(), nullable=True),
                    sa.Column('geo', LongJSONType(), nullable=True),
                    sa.Column('tweet', LongJSONType(), nullable=True),
                    sa.ForeignKeyConstraint(['collection_id'], ['virtual_twitter_collection.id'], ),
                    sa.PrimaryKeyConstraint('id', 'collection_id', 'ttype'),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_general_ci',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('ix_background_tweet_id'), 'background_tweet', ['id'], unique=False)
    op.create_index('tweetcollectionidx', 'background_tweet', ['collection_id', 'ttype', 'lang'], unique=False)
    op.create_table('last_cassandra_export',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('last_tweetid_collected', sa.BigInteger(), nullable=True),
                    sa.Column('last_tweetid_annotated', sa.BigInteger(), nullable=True),
                    sa.Column('last_tweetid_geotagged', sa.BigInteger(), nullable=True),
                    sa.Column('collection_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['collection_id'], ['virtual_twitter_collection.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_general_ci',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_cassandra_export')
    op.drop_index('tweetcollectionidx', table_name='background_tweet')
    op.drop_index(op.f('ix_background_tweet_id'), table_name='background_tweet')
    op.drop_table('background_tweet')
    # ### end Alembic commands ###
