version: "3.5"

services:

  zookeeper:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints: [ node.labels.huge == true ]

  kafka:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 240
      placement:
        constraints: [ node.labels.huge == true ]

  cassandrasmfr:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 60s
      placement:
        constraints: [ node.labels.large == true ]

  geonames:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 120s
      placement:
        constraints: [ node.labels.medium == true ]

  mysql:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints: [ node.labels.large == true ]
