FROM python:3.6
MAINTAINER Domenico Nappo <domenico.nappo@ext.ec.europa.eu>

ARG http_proxy
ARG https_proxy

ENV LANG=C.UTF-8

RUN apt-get update
RUN apt-get -y dist-upgrade
RUN apt-get -yq install net-tools nginx supervisor uwsgi


COPY ./web/requirements.txt /requirements.txt
RUN pip install -U pip && pip install -r /requirements.txt

RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /smfr_clients
COPY ./shared_libs/smfr_clients/. /smfr_clients/
RUN pip3.6 install /smfr_clients/
RUN mkdir -p /smfr_utils
COPY ./shared_libs/smfr_utils/. /smfr_utils/
RUN pip3.6 install /smfr_utils/

RUN rm -R /root/.cache

EXPOSE 8888

# Custom Supervisord config
COPY ./web/conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
# Copy the Nginx global conf
COPY ./web/conf/nginx.conf /etc/nginx/nginx.conf
# Copy the Flask Nginx site conf
COPY ./web/conf/site.conf /etc/nginx/conf.d/site.conf
# Copy the base uWSGI ini file to enable default dynamic uwsgi process number
COPY ./web/conf/uwsgi.ini /etc/uwsgi/uwsgi.ini

ENV INSTALL_PATH /app
RUN mkdir -p $INSTALL_PATH
COPY ./web/src/. $INSTALL_PATH/

CMD ["/usr/bin/supervisord"]