FROM tiangolo/uwsgi-nginx-flask:python3.6
MAINTAINER Domenico Nappo <domenico.nappo@ext.ec.europa.eu>

ENV LANG=C.UTF-8

ENV INSTALL_PATH /app
RUN mkdir -p $INSTALL_PATH

WORKDIR $INSTALL_PATH

COPY ./web/requirements.txt ./

ARG http_proxy
ARG https_proxy

RUN pip install -U pip && pip install -r requirements.txt

RUN mkdir -p /smfr_core
COPY ./shared_libs/smfr_core/. /smfr_core/
RUN pip3.6 install /smfr_core/

ENV LISTEN_PORT 8888
EXPOSE 8888

COPY ./web/conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./web/src/. ./
