version: '3.4'

services:

  geonames:
    build:
      context: ./
      dockerfile: geonames/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    working_dir: /geonames
    container_name: geonames
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    volumes:
      - '${SMFR_DATADIR}/geonames_index:/var/lib/elasticsearch/elasticsearch:rw'

  cassandra:
    image: cassandra:latest
    restart: always
    # From host, connect to DB with `docker exec -it cassandra cqlsh`
    volumes:
      - '${SMFR_DATADIR}/cassandra:/var/lib/cassandra:rw'
    container_name: cassandra
    ports:
      - '9042:9042'
      - '7000:7000'
    cap_add:
      - ALL
    privileged: true
    environment:
      MAX_HEAP_SIZE: 4G
      HEAP_NEWSIZE: 256M

  kafka:
    restart: always
    image: spotify/kafka
    container_name: kafka
    hostname: kafka
    environment:
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST: kafka
    depends_on:
      - cassandra
    ports:
      - '9092:9092'
      - '2181:2181'

  mysql:
    restart: always
    image: mysql:latest
    container_name: mysql
    # From host, connect to DB with `mysql -h 127.0.0.1 -P 3306 -u root -p` (if you have mysql client installed)
    # or using docker exec: `docker exec -it mysql mysql -h 127.0.0.1 -P 3306 -u root -p`
    ports:
      - '3306:3306'
    volumes:
      - '${SMFR_DATADIR}/mysql:/var/lib/mysql:rw'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: smfr
    depends_on:
      - kafka
      - cassandra

  restserver:
    container_name: restserver
    build:
      context: ./
      dockerfile: rest_server/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    working_dir: /rest_server
    environment:
      PYTHONUNBUFFERED: 'true'
      FLASK_APP: smfr.py
      SERVER_PATH_UPLOADS: /smfr/uploads/
      GEONAMES_HOST: geonames
      KERAS_BACKEND: tensorflow
      MYSQL_HOST: mysql
      CASSANDRA_HOST: cassandra
      CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    ports:
      - '5555:5555'
    depends_on:
      - mysql
      - kafka
      - cassandra
      - geonames
    volumes:
      - './rest_server/src:/rest_server'
      - './rest_server/scripts:/scripts'
      - './client:/rest_server/client'
      - './uploads:/smfr/uploads/'

  web:
    container_name: web
    build:
      context: ./
      dockerfile: web/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
    working_dir: /web
    environment:
      PYTHONUNBUFFERED: 'true'
    ports:
      - '8888:8888'
    depends_on:
      - restserver
    volumes:
      - './web/src:/web'
      - './client:/web/client'
