FROM ${WEB_BASE_IMAGE}
MAINTAINER Domenico Nappo <domenico.nappo@ext.ec.europa.eu>

ARG http_proxy
ARG https_proxy

ENV LANG=C.UTF-8

RUN apt-get update && apt-get -y dist-upgrade && apt-get -y install apt-utils \
 && apt-get -y install net-tools nginx supervisor && pip3 install -U pip

# build uwsgi and python plugin
RUN mkdir -p /app && mkdir -p /app/smfrcore && mkdir -p /requirements \
 && mkdir -p /scripts && mkdir -p /uwsgi && cd /uwsgi && wget https://projects.unbit.it/downloads/uwsgi-2.0.15.tar.gz \
 && tar xzvf uwsgi-2.0.15.tar.gz \
 && cd /uwsgi/uwsgi-2.0.15/ && python3.5 uwsgiconfig.py --build core \
 && python3.5 uwsgiconfig.py --plugin plugins/python core && UWSGI_PROFILE=core python3.5 setup.py install \
 && mkdir -p /usr/lib/uwsgi && cp /uwsgi/uwsgi-2.0.15/python_plugin.so /usr/lib/uwsgi/ \
# fix ImportError: No module named '_sysconfigdata_m'
 && ln -fs /usr/lib/python3.5/plat-x86_64-linux-gnu/_sysconfigdata_m.py /usr/lib/python3.5/

COPY ./web/requirements.txt /requirements/requirements.txt
RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY base/shared_libs/scripts/wait_for_it.sh /scripts/
COPY base/shared_libs/smfr_utils/. /smfr_libs/utils/
COPY base/shared_libs/smfr_clients/. /smfr_libs/clients/

RUN pip3 install -r /requirements/requirements.txt
RUN pip3 install /smfr_libs/utils/ \
 && pip3 install /smfr_libs/clients/ \
 && chmod -R a+x /scripts/ && rm -R /root/.cache

EXPOSE 8888

# Custom Supervisord config
COPY ./web/conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
# Copy the Nginx global conf
COPY ./web/conf/nginx.conf /etc/nginx/nginx.conf
# Copy the Flask Nginx site conf
COPY ./web/conf/site.conf /etc/nginx/conf.d/site.conf
# Copy the base uWSGI ini file to enable default dynamic uwsgi process number
COPY ./web/conf/uwsgi.ini /etc/uwsgi/uwsgi.ini

COPY ./web/src/. /app/

WORKDIR /app
ENTRYPOINT ["/scripts/wait_for_it.sh", "restserver:5555"]
CMD ["--", "/usr/bin/supervisord"]
