swagger: '2.0'
info:
  title: SMFR Rest Server
  description: SMFR Rest API
  version: '1.0'
consumes:
  - application/json
produces:
  - application/json

paths:

  /collections:
    post:
      tags: [collections]
      operationId: server.api.collections.add_collection
      summary: Submit a new collection
      consumes:
        - multipart/form-data
      parameters:
        - in: body
          name: payload
          schema:
            $ref: '#/definitions/CollectorPayload'
        - in: formData
          name: kwfile
          type: file
          description: File with keywords by language
        - in: formData
          name: locfile
          type: file
          description: File with bounding boxes
        - in: formData
          name: config
          type: file
          description: Configuration file for Collector
      responses:
        200:
          description: Return collectors
          schema:
            type: object
            $ref: '#/definitions/CollectorResponse'
    get:
      tags: [collections]
      operationId: server.api.collections.get
      summary: Get all collections defined in SMFR
      responses:
        200:
          description: Return collectors
          schema:
            type: array
            items:
              $ref: '#/definitions/CollectorResponse'

  /collections/active:
    get:
      tags: [collections]
      operationId: server.api.collections.get_running_collectors
      summary: Get running collectors
      responses:
        200:
          description: Return collectors
          schema:
            type: array
            items:
              $ref: '#/definitions/CollectorResponse'

  /collections/inactive:
    get:
      tags: [collections]
      operationId: server.api.collections.get_stopped_collectors
      summary: Get inactive collections
      responses:
        200:
          description: Return inactive collectors
          schema:
            type: array
            items:
              $ref: '#/definitions/CollectorResponse'

  /collections/start/{collector_id}:
    post:
      tags: [collections]
      operationId: server.api.collections.start_collector
      parameters:
        - in: path
          name: collector_id
          type: integer
          required: true
          description: Numeric ID of the stored collector to start.
      summary: Start a previously defined collector
      responses:
        204:
          description: The collector was started successfully.

  /collections/stop/{collector_id}:
    post:
      tags: [collections]
      operationId: server.api.collections.stop_collector
      parameters:
        - in: path
          name: collector_id
          type: integer
          required: true
          description: Numeric ID of the stored collector to start.
      summary: Stop a previously defined and running collector
      responses:
        204:
          description: The collector was stopped successfully.

  /collections/{collection_id}/remove:
    post:
      tags: [collections]
      operationId: server.api.collections.remove_collection
      parameters:
        - in: path
          name: collection_id
          type: integer
          required: true
          description: Collection ID as stored in MySQL DB
      summary: Remove a collection from the system
      responses:
        204:
          description: The collection was removed successfully

  /collections/{collection_id}/details:
    get:
      tags: [collections]
      operationId: server.api.collections.get_collection_details
      parameters:
        - in: path
          name: collection_id
          type: integer
          required: true
          description: Collection ID as stored in MySQL DB
      summary: Details of a collection
      responses:
        200:
          description: The collection was removed successfully
          schema:
            type: object
            $ref: '#/definitions/CollectionResponse'

  /collections/{collection_id}/geo:
    post:
      tags: [collections]
      operationId: server.api.collections.geolocalize
      parameters:
        - in: path
          name: collection_id
          type: integer
          required: true
          description: Collection ID as stored in MySQL DB
        - in: query
          name: startdate
          type: string
          format: date-time
          description: Start date
        - in: query
          name: enddate
          type: string
          format: date-time
          description: End date
      summary: Start Geotagging annotated tweets for this collection
      responses:
        204:
          description: Annotated tweets are starting to be geotagged...

  /collections/{collection_id}/annotate:
    post:
      tags: [collections]
      operationId: server.api.collections.annotate
      parameters:
        - in: path
          name: collection_id
          type: integer
          required: true
          description: Collection ID as stored in MySQL DB
        - in: query
          name: lang
          type: string
          description: Language model to use for annotations
          required: true
          default: en
        - in: query
          name: forecast_id
          type: integer
          description: forecast id (e.g. 201804111200)
        - in: query
          name: startdate
          type: string
          format: date-time
          description: Start date
        - in: query
          name: enddate
          type: string
          format: date-time
          description: End date
      summary: Annotate (classify) tweets for this collection
      responses:
        204:
          description: Collected tweets are starting to be annotated...

  /collections/startall:
    post:
      tags: [collections]
      operationId: server.api.collections.start_all
      summary: Start all inactive collections defined in the system
      responses:
        204:
          description: Collectors were started successfully

  /collections/stopall:
    post:
      tags: [collections]
      operationId: server.api.collections.stop_all
      summary: Stop all active collections defined in the system
      responses:
        204:
          description: Collectors were stopped successfully


definitions:

  Collection:
    type: object
    properties:
      id:
        type: integer
      trigger:
        type: string
        enum: [background, on-demand, manual]
      ctype:
        type: string
        enum: [keywords, geo]
      forecast_id:
        type: string
      tracking_keywords:
        type: array
        items:
          type: string
      locations:
        type: string
      languages:
        type: array
        items:
          type: string
      runtime:
        type: string
        format: date-time
      nuts3:
        type: string
      nuts3source:
        type: string
      status:
        type: string
        enum: [active, inactive]
      started_at:
        type: string
        format: date-time
      stopped_at:
        type: string
        format: date-time

  CollectorPayload:
    type: object
    required: [trigger]
    properties:
      trigger:
        type: string
        enum: [background, on-demand, manual]
      forecast_id:
        type: string
      runtime:
        type: string
        format: date-time
      nuts3:
        type: string
      nuts3source:
        type: string

  CollectorResponse:
    type: object
    properties:
      collection:
        $ref: '#/definitions/Collection'
      id:
        type: integer

  Collector:
    type: object
    properties:
      id:
        type: integer
      collection_id:
        type: integer
      parameters:
        type: string

  CollectionStats:
    type: object
    properties:
      tweets_count:
        type: integer
      tweets_annotated:
        type: integer
      tweets_geotagged:
        type: integer
      tweets_day_avg:
        type: number
        format: float

  CollectionTweetSample:
    type: object
    required:
      - tweetid
      - tweet
      - created_at
    properties:
      tweetid:
        type: string
      collectionid:
        type: integer
      tweet:
        type: object
      annotations:
        type: object
      nuts3:
        type: string
      latlong:
        type: array
        items:
          type: number
          format: float
        minItems: 2
        maxItems: 2
      ttype:
        type: string
        enum: [annotated, collected, geotagged]
      created_at:
        type: string
        format: date-time


  CollectionResponse:
    type: object
    properties:
      collection:
        $ref: '#/definitions/Collection'
      collector:
        $ref: '#/definitions/Collector'
      stats:
        $ref: '#/definitions/CollectionStats'
      running_annotators:
        type: array
        items:
          type: object
      samples:
        type: array
        items:
          $ref: '#/definitions/CollectionTweetSample'
