it:
  - inondato
  - inondazione
  - inondazioni
  - tempesta
  - bomba d'acqua
  - esondazione
  - allagamento
  - forti piogge
  - piogge torrenziali
  - allagato
  - allagata
  - alluvione
  - alluvioni
  - esondazioni
  - fiume in piena
  - rotto gli argini
  - straripamento
  - straripare
  - diluvio
en:
  - flood
  - floods
  - flooding
  - flooded
  - inundation
  - waterlogged
  - waterlogging
  - drainage
  - drain system
  - urban drain
  - heavy rain
  - heavy rains
  - extreme rainfall
  - sewage overflow
  - river overflow
  - rain overflow
  - water overflow
es:
  - inundación
  - inundacion
  - inundaciones
  - inundado
  - inundada
  - anegado
  - anegada
  - sistema de drenaje
  - urbano de drenaje
  - muy lluvioso
  - muy lluviosa
  - fuertes lluvias
  - fuerte lluvia
  - desbordamiento
  - desborde alcantarillas
  - desborde colector
  - desborde rio
  - desborde río
  - desborde lluvia
  - desborde agua
de:
  - Hochwasser
  - Überschwemmung
  - Uberschwemmung
  - Ueberschwemmung
  - Überschwemmungen
  - Uberschwemmungen
  - Ueberschwemmungen
  - Überflutung
  - Uberflutung
  - Ueberflutung
  - Überflutungen
  - Uberflutungen
  - Ueberflutungen
  - überflutet
  - uberflutet
  - ueberflutet
  - Sturmflut
  - wasserstand in
  - der wasserstand
  - meteorologen warnen
  - hochwasserinfo
  - wasser bereits
  - starken Regen
  - Starkregen
  - Kanalisation hochgedrückt
fr:
  - inondation
  - inondations
  - d’inondation
  - d'inondation
  - l'inondation
  - l’inondation
  - inondé
  - inonde
  - crue
  - décrue
  - decrue
  - forte pluie
  - fortes pluies
  - orages
  - débordement
  - niveau d'eau
  - vigilance crue
  - vigilance pluie
  - meteo vigilance
  - météo vigilance
  - vigilance submersion
  - vigilance vagues