"""empty message

Revision ID: 1164223db0bf
Revises: 253cd49e8363
Create Date: 2019-01-14 14:03:36.873842

"""
from alembic import op
import sqlalchemy as sa

from smfrcore.models.sql.base import LongJSONType

# revision identifiers, used by Alembic.
revision = '1164223db0bf'
down_revision = '253cd49e8363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('efas_cycle', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('trends', LongJSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'trends')
    op.drop_column('product', 'efas_cycle')
    # ### end Alembic commands ###
