"""empty message

Revision ID: 253cd49e8363
Revises: 14ee6feb7870
Create Date: 2019-01-09 17:19:59.221141

"""
from alembic import op
import sqlalchemy as sa

from smfrcore.models.sql.base import LongJSONType

# revision identifiers, used by Alembic.
revision = '253cd49e8363'
down_revision = '14ee6feb7870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregation', sa.Column('trends', LongJSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aggregation', 'trends')
    # ### end Alembic commands ###
