"""empty message

Revision ID: c4ac6d20d6f1
Revises: 461a504ec8a4
Create Date: 2018-09-10 11:50:45.091413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4ac6d20d6f1'
down_revision = '461a504ec8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('virtual_twitter_collection_ibfk_1', 'virtual_twitter_collection', type_='foreignkey')
    op.drop_column('virtual_twitter_collection', 'configuration_id')
    op.drop_table('collector_configuration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_configuration',
                    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
                    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=500), nullable=True),
                    sa.Column('consumer_key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
                              nullable=False),
                    sa.Column('consumer_secret', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
                              nullable=False),
                    sa.Column('access_token', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
                              nullable=False),
                    sa.Column('access_token_secret', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
                              nullable=False),
                    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='collector_configuration_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_general_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.add_column('virtual_twitter_collection',
                  sa.Column('configuration_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('virtual_twitter_collection_ibfk_1', 'virtual_twitter_collection', 'collector_configuration',
                          ['configuration_id'], ['id'])

    # ### end Alembic commands ###
