"""empty message

Revision ID: e6a1825635e2
Revises: c4ac6d20d6f1
Create Date: 2018-09-28 17:17:04.041294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6a1825635e2'
down_revision = 'c4ac6d20d6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aggregation', 'values',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_general_ci'),
               nullable=False)
    op.create_foreign_key(None, 'virtual_twitter_collection', 'users', ['user_id'], ['id'])
    op.drop_column('virtual_twitter_collection', 'configuration_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_twitter_collection', sa.Column('configuration_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'virtual_twitter_collection', type_='foreignkey')
    op.alter_column('aggregation', 'values',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_general_ci'),
               nullable=True)
    # ### end Alembic commands ###
