"""empty message

Revision ID: 0fd6c3f4f5a5
Revises: 03e961ff91b8
Create Date: 2018-07-31 16:52:49.452032

"""
import os

import yaml
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from smfrcore.models.sqlmodels import CollectorConfiguration

# revision identifiers, used by Alembic.
revision = '0fd6c3f4f5a5'
down_revision = '03e961ff91b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_configuration',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=500), nullable=True),
                    sa.Column('consumer_key', sa.String(length=200), nullable=False),
                    sa.Column('consumer_secret', sa.String(length=200), nullable=False),
                    sa.Column('access_token', sa.String(length=200), nullable=False),
                    sa.Column('access_token_secret', sa.String(length=200), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_general_ci',
                    mysql_engine='InnoDB'
                    )
    config_table = CollectorConfiguration.__table__
    path = os.path.join(os.path.dirname(__file__), '../../config/admin_collector.yaml')
    with open(path) as f:
        init_data = yaml.load(f)
        init_data['twitterbg']['name'] = 'admin'
        init_data['twitterod']['name'] = 'admin1'
        data = [init_data['twitterbg'], init_data['twitterod']]
        op.bulk_insert(config_table, data)
    op.add_column('virtual_twitter_collection', sa.Column('configuration_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'virtual_twitter_collection', 'collector_configuration', ['configuration_id'], ['id'])
    op.drop_column('virtual_twitter_collection', 'ctype')
    op.drop_column('virtual_twitter_collection', 'nuts2source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_twitter_collection',
                  sa.Column('nuts2source', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('virtual_twitter_collection',
                  sa.Column('ctype', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_constraint(None, 'virtual_twitter_collection', type_='foreignkey')
    op.drop_column('virtual_twitter_collection', 'configuration_id')
    op.drop_table('collector_configuration')
    # ### end Alembic commands ###
