"""empty message

Revision ID: 1126dcc35270
Revises: 0fd6c3f4f5a5
Create Date: 2018-08-01 10:24:44.158386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1126dcc35270'
down_revision = '0fd6c3f4f5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_collector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_collector',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('collection_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('parameters', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['virtual_twitter_collection.id'], name='stored_collector_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
