"""empty message

Revision ID: 1bfd88d3172a
Revises: f5f82e17f8f8
Create Date: 2018-02-07 11:47:50.097469

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1bfd88d3172a'
down_revision = 'f5f82e17f8f8'
branch_labels = None
depends_on = None


def upgrade():
    import sqlalchemy_utils
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_collector',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('collection_id', sa.Integer(), nullable=True),
                    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
                    sa.ForeignKeyConstraint(['collection_id'], ['virtual_twitter_collection.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_general_ci',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_collector')
    # ### end Alembic commands ###
