"""empty message

Revision ID: 1c37569dd337
Revises: 1bfd88d3172a
Create Date: 2018-02-26 14:57:36.694514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c37569dd337'
down_revision = '1bfd88d3172a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_twitter_collection', sa.Column('runtime', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_twitter_collection', 'runtime')
    # ### end Alembic commands ###
