"""empty message

Revision ID: 22827e81f3f2
Revises: 8be028315675
Create Date: 2018-05-17 17:41:57.085336

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '22827e81f3f2'
down_revision = '1c37569dd337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=True),
                    sa.Column('email', sa.String(length=100), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_general_ci',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('virtual_twitter_collection', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'virtual_twitter_collection', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'virtual_twitter_collection', type_='foreignkey')
    op.drop_column('virtual_twitter_collection', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
