"""empty message

Revision ID: 2292efe3e3e6
Revises: a65c4b058597
Create Date: 2018-07-17 08:26:39.427396

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.

revision = '2292efe3e3e6'
down_revision = 'a65c4b058597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('bbox_index', 'nuts2', ['min_lon', 'min_lat', 'max_lon', 'max_lat'], unique=True)

    op.alter_column('virtual_twitter_collection', 'nuts3', new_column_name='nuts2', existing_type=sa.types.String(50))
    op.alter_column('virtual_twitter_collection', 'nuts3source', new_column_name='nuts2source', existing_type=sa.types.String(255))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('virtual_twitter_collection', 'nuts2', new_column_name='nuts3', existing_type=sa.types.String(50))
    op.alter_column('virtual_twitter_collection', 'nuts2source', new_column_name='nuts3source', existing_type=sa.types.String(255))
    op.drop_index('bbox_index', table_name='nuts2')
    # ### end Alembic commands ###
