"""empty message

Revision ID: 3adda90c1d1f
Revises: a6dd1489ef40
Create Date: 2018-07-20 15:55:56.595584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3adda90c1d1f'
down_revision = 'a6dd1489ef40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregation', sa.Column('last_tweetid_annotated', sa.BigInteger(), nullable=True))
    op.add_column('aggregation', sa.Column('last_tweetid_collected', sa.BigInteger(), nullable=True))
    op.add_column('aggregation', sa.Column('last_tweetid_geotagged', sa.BigInteger(), nullable=True))
    op.drop_column('aggregation', 'last_tweetid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregation', sa.Column('last_tweetid', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_column('aggregation', 'last_tweetid_geotagged')
    op.drop_column('aggregation', 'last_tweetid_collected')
    op.drop_column('aggregation', 'last_tweetid_annotated')
    # ### end Alembic commands ###
