"""empty message

Revision ID: 80ba1ee8df05
Revises: 3adda90c1d1f
Create Date: 2018-07-23 12:18:47.645761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ba1ee8df05'
down_revision = '3adda90c1d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregation', sa.Column('timestamp_end', sa.TIMESTAMP(), nullable=True))
    op.add_column('aggregation', sa.Column('timestamp_start', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aggregation', 'timestamp_start')
    op.drop_column('aggregation', 'timestamp_end')
    # ### end Alembic commands ###
