"""empty message

Revision ID: 8be028315675
Revises: 1c37569dd337
Create Date: 2018-04-11 11:29:57.987179

"""
import os

import ujson as json

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8be028315675'
down_revision = '1c37569dd337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bbox_table = op.create_table('nuts_bounding_box',
                                 sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
                                 sa.Column('min_lon', sa.Float(), nullable=True),
                                 sa.Column('max_lon', sa.Float(), nullable=True),
                                 sa.Column('min_lat', sa.Float(), nullable=True),
                                 sa.Column('max_lat', sa.Float(), nullable=True),
                                 sa.PrimaryKeyConstraint('id')
                                 )
    # ### end Alembic commands ###
    path = os.path.join(os.path.dirname(__file__), './bbox_init.json')
    with open(path) as init_f:
        init_data = json.load(init_f, precise_float=True)
        op.bulk_insert(bbox_table, init_data)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nuts_bounding_box')
    # ### end Alembic commands ###
