"""empty message

Revision ID: a65c4b058597
Revises: 71fed9a0a869
Create Date: 2018-07-13 10:06:37.641157

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a65c4b058597'
down_revision = '71fed9a0a869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('collection_id', sa.Integer(), nullable=True),
                    sa.Column('values', sqlalchemy_utils.types.json.JSONType(), nullable=False),
                    sa.ForeignKeyConstraint(['collection_id'], ['virtual_twitter_collection.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_general_ci',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aggregation')
    # ### end Alembic commands ###
