"""empty message

Revision ID: a6dd1489ef40
Revises: 355e9e5e4d00
Create Date: 2018-07-20 15:40:39.223569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6dd1489ef40'
down_revision = '355e9e5e4d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aggregation', 'last_tweetid',
                    existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aggregation', 'last_tweetid',
                    existing_type=sa.BigInteger(),
                    type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
                    existing_nullable=True)
    # ### end Alembic commands ###
