"""empty message

Revision ID: ba194f1bbc32
Revises: 34ad35a774d2
Create Date: 2018-08-14 14:07:49.466233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba194f1bbc32'
down_revision = '34ad35a774d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collector_configuration', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collector_configuration', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collector_configuration', type_='foreignkey')
    op.drop_column('collector_configuration', 'user_id')
    # ### end Alembic commands ###
