"""empty message

Revision ID: baff15f41cc3
Revises: d89c50fcc240
Create Date: 2018-02-01 13:01:28.343572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baff15f41cc3'
down_revision = 'd89c50fcc240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_twitter_collection', sa.Column('nuts3', sa.String(length=50), nullable=True))
    op.add_column('virtual_twitter_collection', sa.Column('nuts3source', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_twitter_collection', 'nuts3source')
    op.drop_column('virtual_twitter_collection', 'nuts3')
    # ### end Alembic commands ###
