"""empty message

Revision ID: d89c50fcc240
Revises: 
Create Date: 2018-02-01 11:31:01.811066

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89c50fcc240'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from server.models import VirtualTwitterCollection
    op.create_table('virtual_twitter_collection',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sqlalchemy_utils.types.choice.ChoiceType(VirtualTwitterCollection.TRIGGERS), nullable=False),
    sa.Column('ctype', sqlalchemy_utils.types.choice.ChoiceType(VirtualTwitterCollection.TYPES), nullable=False),
    sa.Column('tracking_keywords', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
    sa.Column('locations', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('languages', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(VirtualTwitterCollection.STATUSES), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_twitter_collection')
    # ### end Alembic commands ###
