"""empty message

Revision ID: d9de6ad59528
Revises: 22827e81f3f2
Create Date: 2018-06-11 16:08:25.692658

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils

from smfrcore.models.sqlmodels import User
# revision identifiers, used by Alembic.
revision = 'd9de6ad59528'
down_revision = '22827e81f3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType(User.ROLES), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
