"""empty message

Revision ID: f5f82e17f8f8
Revises: baff15f41cc3
Create Date: 2018-02-02 10:14:24.514113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f82e17f8f8'
down_revision = 'baff15f41cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_twitter_collection', sa.Column('started_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('virtual_twitter_collection', sa.Column('stopped_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_twitter_collection', 'stopped_at')
    op.drop_column('virtual_twitter_collection', 'started_at')
    # ### end Alembic commands ###
