"""empty message

Revision ID: f99ee53dfd20
Revises: d9de6ad59528
Create Date: 2018-06-19 11:36:19.246647

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f99ee53dfd20'
down_revision = 'd9de6ad59528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'nuts3',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('efas_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=500), nullable=False),
        sa.Column('name_ascii', sa.String(length=500), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('names', sqlalchemy_utils.types.json.JSONType(), nullable=False),
        sa.Column('properties', sqlalchemy_utils.types.json.JSONType(), nullable=False),
        sa.Column('country_name', sa.String(length=500), nullable=False),
        sa.Column('nuts_id', sa.String(length=10), nullable=True),
        sa.Column('country_code', sa.String(length=5), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_charset='utf8mb4',
        mysql_collate='utf8mb4_general_ci',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_nuts3_efas_id'), 'nuts3', ['efas_id'], unique=False)
    op.create_index(op.f('ix_nuts3_name_ascii'), 'nuts3', ['name_ascii'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nuts3_name_ascii'), table_name='nuts3')
    op.drop_index(op.f('ix_nuts3_efas_id'), table_name='nuts3')
    op.drop_table('nuts3')
    # ### end Alembic commands ###
